apiVersion: kubeovn.io/v1
kind: IptablesEIP
metadata:
  name: eip-__user_name
spec:
  v4ip: __user_vmr
  natGwDp: gateway-__user_name
---
apiVersion: kubeovn.io/v1
kind: IptablesSnatRule
metadata:
  name: snat-__user_name
spec:
  eip: eip-__user_name
  internalCIDR: 10.10.10.0/24
