apiVersion: v1
kind: Pod
metadata:
  namespace: ns-__user_name
  name: __vmname
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-__user_name
    ovn.kubernetes.io/ip_address: __fix_ipaddress_all
spec:
  nodeSelector:
    kubernetes.io/hostname: __select_node
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.16.255.254
      - 114.114.114.114
  containers:
  - name: __vmname
    image: qemux/qemu-docker
    ports:
      - containerPort: 8006
        protocol: TCP
    securityContext:
      privileged: true
    env:
      - name: RAM_SIZE
        value: "16G"
      - name: CPU_CORES
        value: "8"
      - name: DISK_SIZE
        value: "80G"
      - name: DISK_FMT
        value: "qcow2"
    volumeMounts:
      - mountPath: /storage
        name: storage
      - mountPath: /dev/kvm
        name: kvm
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: __vmname-pvc
    - name: kvm
      hostPath:
        path: /dev/kvm
---
apiVersion: kubeovn.io/v1
kind: IptablesDnatRule
metadata:
  name: dnat-__user_name-__fix_ipaddress_nf22
spec:
  eip: eip-__user_name
  externalPort: "__fix_ipaddress_nf22"
  protocol: tcp
  internalIp: __fix_ipaddress_all
  internalPort: "22"
---
apiVersion: kubeovn.io/v1
kind: IptablesDnatRule
metadata:
  name: dnat-__user_name-__fix_ipaddress_nf80
spec:
  eip: eip-__user_name
  externalPort: "__fix_ipaddress_nf80"
  protocol: tcp
  internalIp: __fix_ipaddress_all
  internalPort: "80"
