apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-__user_name
    ovn.kubernetes.io/ip_address: __fix_ipaddress_all
  namespace: ns-__user_name
  name: __vmname
spec:
  nodeSelector:
    kubernetes.io/hostname: __select_node
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.16.255.254
      - 114.114.114.114
  containers:
    - name: __vmname
      image: registry.jxit.net.cn:5000/qdcloud/jxcentos:7@sha256:9e6366f5568060050a286cc0410a70fdbf0044e3e58501bda8ea37dcb9ddf225
      securityContext:
        privileged: true
---
apiVersion: kubeovn.io/v1
kind: IptablesDnatRule
metadata:
  name: dnat-__user_name-__fix_ipaddress_nf22
spec:
  eip: eip-__user_name
  externalPort: "__fix_ipaddress_nf22"
  protocol: tcp
  internalIp: __fix_ipaddress_all
  internalPort: "22"
---
apiVersion: kubeovn.io/v1
kind: IptablesDnatRule
metadata:
  name: dnat-__user_name-__fix_ipaddress_nf80
spec:
  eip: eip-__user_name
  externalPort: "__fix_ipaddress_nf80"
  protocol: tcp
  internalIp: __fix_ipaddress_all
  internalPort: "80"
