apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __vmname-pvc
  namespace: ns-__user_name
spec:
  storageClassName:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
