apiVersion: v1
kind: Namespace
metadata:
  name: ns-__user_name
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc-__user_name
spec:
  namespaces:
  - ns-__user_name
  staticRoutes:
  - cidr: 0.0.0.0/0
    nextHopIP: 10.10.10.254
    policy: policyDst
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet-__user_name
spec:
  vpc: vpc-__user_name
  gateway: 10.10.10.254
  cidrBlock: 10.10.10.0/24
  protocol: IPv4
  namespaces:
    - ns-__user_name
