apiVersion: v1
kind: Pod
metadata:
  name: centos7
spec:
  containers:
  - env:
    - name: RAM_SIZE
      value: 16G
    - name: CPU_CORES
      value: "8"
    - name: DISK_SIZE
      value: 16G
    - name: DISK_FMT
      value: qcow2
    image: registry.jxit.net.cn:5000/docker.io/qemux/qemu-docker
    imagePullPolicy: Always
    name: centos7
    ports:
    - containerPort: 8006
      protocol: TCP
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /storage
      name: storage
    - mountPath: /dev/kvm
      name: kvm
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: centos7-pvc
  - hostPath:
      path: /dev/kvm
      type: ""
    name: kvm
