apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: Service
metadata:
  name: windows
spec:
  type: NodePort
  selector:
    app: windows
  ports:
    - name: tcp-8006
      protocol: TCP
      port: 8006
      targetPort: 8006
      nodePort: 31806
    - name: tcp-3389
      protocol: TCP
      port: 3389
      targetPort: 3389
      nodePort: 31389
    - name: udp-3389
      protocol: UDP
      port: 3389
      targetPort: 3389
      nodePort: 31388
---
apiVersion: v1
kind: Pod
metadata:
  name: windows
  labels:
    app: windows
spec:
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: windows-pvc
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 120
  containers:
  - name: windows
    image: dockurr/windows
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    resources:
      limits:
        cpu: '10'
        memory: 22Gi
      requests:
        cpu: 8250m
        memory: 16512Mi
    env:
    - name: VERSION
      value: "2016"
    ports:
    - name: vnc
      containerPort: 8006
      protocol: TCP
    - name: rdp-tcp
      containerPort: 3389
      protocol: TCP
    - name: rdp-udp
      containerPort: 3389
      protocol: UDP
    volumeMounts:
    - name: storage
      mountPath: /storage
    - name: kvm
      mountPath: /dev/kvm
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: windows-pvc
  - name: kvm
    hostPath:
      path: /dev/kvm
